import { startRecipeImageCacheCleanup } from '@/lib/recipe-image-cache';
import { startImageCacheCleanup } from '@/lib/server-image-cache';
import { sessionLimitsManager } from '@/lib/sessionLimits';
import {
  GenerateRecipeRequest,
  generateRecipeRequestSchema,
  getFirstZodError,
  safeValidateSchema,
} from '@/schemas';
import {
  generateMultipleRecipesWithGemini,
  generateRecipeWithGemini,
} from '@/services/geminiService';
import { generateRecipeWithOpenAI, isOpenAIServiceAvailable } from '@/services/openaiRecipeService';
import { deduplicateIngredients, filterDuplicateIngredients } from '@/utils/ingredientUtils';
import { NextRequest, NextResponse } from 'next/server';

// Declarar tipo para el cache global del servidor
declare global {
  var serverCache: Map<string, any> | undefined;
  var imageCacheInitialized: boolean | undefined;
  var recipeImageCacheInitialized: boolean | undefined;
}

export async function POST(request: NextRequest) {
  // Initialize image cache cleanup if not already done
  if (!global.imageCacheInitialized) {
    startImageCacheCleanup();
    global.imageCacheInitialized = true;
    console.log('🔄 Image cache cleanup initialized');
  }

  // Initialize recipe image cache cleanup if not already done
  if (!global.recipeImageCacheInitialized) {
    startRecipeImageCacheCleanup();
    global.recipeImageCacheInitialized = true;
    console.log('🔄 Recipe image cache cleanup initialized');
  }

  let ingredients: string[] = [];
  let servings: number = 2;
  let cuisine: string = 'international';
  let count: number = 1;
  let customTitle: string | undefined = undefined;
  let userId: string | undefined = undefined;

  try {
    const requestData = await request.json();
    console.log('🔍 API Route - Raw request body:', JSON.stringify(requestData, null, 2));

    // Validar los datos de entrada con Zod
    const validation = safeValidateSchema(generateRecipeRequestSchema, requestData);
    if (!validation.success) {
      return NextResponse.json(
        {
          error: 'Validation failed',
          details: getFirstZodError(validation.error),
        },
        { status: 400 }
      );
    }

    const validatedData = validation.data as GenerateRecipeRequest;
    ({ ingredients, servings, cuisine, count, title: customTitle, userId } = validatedData);

    console.log('🔍 API Route - Received data:', {
      ingredients,
      servings,
      count,
      userId,
      hasUserId: !!userId,
    });

    // 🚫 SESSION LIMIT CHECK: Verificar límite de recetas por sesión
    if (userId) {
      console.log('🔍 Checking session limit for userId:', userId);
      const canGenerate = sessionLimitsManager.canGenerateRecipe(userId);
      console.log('🔍 Can generate recipe:', canGenerate);

      if (!canGenerate) {
        const remaining = sessionLimitsManager.getRemainingRecipes(userId);
        console.log('🚫 Daily limit exceeded for userId:', userId, 'remaining:', remaining);
        return NextResponse.json(
          {
            error: 'Daily limit exceeded',
            message: `You have reached today's recipe limit (1 recipe per day). Please try again tomorrow.`,
            remainingRecipes: remaining,
            limitExceeded: true,
            resetTime: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(), // 24 hours from now
          },
          { status: 429 } // Too Many Requests
        );
      }
    } else {
      console.log('⚠️ No userId provided, skipping session limit check');
    }

    // 🚀 CACHE CHECK: Verificar si ya tenemos recetas en cache (servidor)
    console.log('🔍 Checking server cache for ingredients:', ingredients, 'servings:', servings);
    const cacheKey = `recipes_${ingredients.sort().join(',')}_${servings}`;

    // Cache simple en memoria del servidor
    if (!global.serverCache) {
      global.serverCache = new Map();
    }

    const cachedRecipes = global.serverCache.get(cacheKey);
    if (cachedRecipes && cachedRecipes.length > 0) {
      console.log('✅ Using server cached recipes:', cachedRecipes.length, 'recipes');
      return NextResponse.json({
        recipes: cachedRecipes,
        count: cachedRecipes.length,
        source: 'server-cache',
      });
    } else {
      console.log('❌ No server cached recipes found, will generate new ones');
    }

    let recipes;
    let source = 'gemini';

    // Primary: Gemini 2.5 Flash (free). OpenAI is only an optional fallback.
    try {
      console.log('🔄 Using Gemini 2.5 Flash for recipe generation (free)');
      if (count && count > 1) {
        recipes = await generateMultipleRecipesWithGemini(ingredients, servings, count);
      } else {
        const recipe = await generateRecipeWithGemini(ingredients, servings, cuisine);
        recipes = [recipe];
      }
      if (!recipes || recipes.length === 0) {
        throw new Error('No recipes generated by Gemini');
      }
      source = 'gemini';
    } catch (error) {
      console.error('Gemini recipe generation failed:', error);
      // Optional fallback to OpenAI only if a key is configured
      if (isOpenAIServiceAvailable()) {
        console.log('↩️ Falling back to OpenAI for recipe generation');
        const openaiResponse = await generateRecipeWithOpenAI({
          ingredients,
          servings,
          cuisine,
          count: count || 1,
          title: customTitle,
        });
        recipes = openaiResponse.recipes;
        source = 'openai-fallback';
      } else {
        throw error;
      }
    }

    // Assign IDs/titles + a COHERENT food photo. Prefer Pexels (free API key,
    // searched by the dish name → relevant photo); fall back to a free
    // loremflickr stock photo when PEXELS_API_KEY is missing or the lookup
    // fails. No paid image APIs.
    const STOP_WORDS = new Set([
      'with','and','the','for','a','an','of','in','on','to','style','recipe','homemade','fresh','easy',
    ]);

    const fetchPexelsImages = async (
      query: string,
      count: number
    ): Promise<string[]> => {
      const key = process.env.PEXELS_API_KEY;
      if (!key) return [];
      try {
        const res = await fetch(
          `https://api.pexels.com/v1/search?query=${encodeURIComponent(
            query
          )}&per_page=${count}&orientation=landscape`,
          { headers: { Authorization: key } }
        );
        if (!res.ok) return [];
        const data = await res.json();
        const photos = (data?.photos as Array<{ src?: Record<string, string> }>) || [];
        return photos
          .map(p => p?.src?.large || p?.src?.landscape || p?.src?.medium)
          .filter((u): u is string => Boolean(u));
      } catch {
        return [];
      }
    };

    // Keyless coherent fallback: TheMealDB returns REAL dish photos. Prefer
    // filter-by-ingredient (best coverage: chicken/rice/beef/tomato…), then
    // search-by-dish-name. Avoids loremflickr's junk default for unmatched
    // multi-keyword queries.
    const mealDbThumbs = async (url: string): Promise<string[]> => {
      try {
        const res = await fetch(url);
        if (!res.ok) return [];
        const data = await res.json();
        const meals = (data?.meals as Array<{ strMealThumb?: string }>) || [];
        return meals
          .map(m => m?.strMealThumb)
          .filter((u): u is string => Boolean(u));
      } catch {
        return [];
      }
    };
    const fetchMealDbImages = async (
      ingredients: string[],
      nameTerms: string[],
      count: number
    ): Promise<string[]> => {
      const base = 'https://www.themealdb.com/api/json/v1/1';
      // 1) By main ingredient (real dishes that contain it).
      for (const ing of ingredients) {
        const clean = ing.replace(/[^a-zA-Z ]/g, '').trim();
        const word = clean.split(/\s+/).pop() || clean; // "chicken breast" → "chicken"
        if (word.length < 3) continue;
        const thumbs = await mealDbThumbs(
          `${base}/filter.php?i=${encodeURIComponent(word)}`
        );
        if (thumbs.length > 0) return thumbs.slice(0, count);
      }
      // 2) By dish name / cuisine word.
      for (const term of nameTerms) {
        if (!term || term.length < 3) continue;
        const thumbs = await mealDbThumbs(
          `${base}/search.php?s=${encodeURIComponent(term)}`
        );
        if (thumbs.length > 0) return thumbs.slice(0, count);
      }
      return [];
    };

    const recipesWithImages = await Promise.all(
      recipes.map(async (recipe, index) => {
        const finalTitle =
          customTitle && index === 0
            ? customTitle
            : recipe?.title || `Generated Recipe ${index + 1}`;
        const recipeId = `recipe_${Date.now()}_${Math.random()
          .toString(36)
          .substr(2, 9)}`;

        // Main words from the dish title → the most descriptive image query.
        const titleWords = finalTitle
          .toLowerCase()
          .replace(/[^a-z0-9\s]/g, ' ')
          .split(/\s+/)
          .filter(w => w.length > 2 && !STOP_WORDS.has(w));

        // 1) Try Pexels (coherent, free with a key): ONE call returns several
        //    photos of the dish — first is the main image, rest are the steps.
        const pexelsQuery = [...titleWords.slice(0, 4), recipe?.cuisine, 'food']
          .filter(Boolean)
          .join(' ');
        let photos = await fetchPexelsImages(pexelsQuery, 6);
        let imageSource = 'pexels';

        // 2) Keyless coherent fallback: TheMealDB real dish photos.
        if (photos.length === 0) {
          const ingredientNames = (
            (recipe?.ingredients as Array<{ name?: string }>) || []
          )
            .map(i => i?.name)
            .filter((n): n is string => Boolean(n))
            .slice(0, 4);
          const nameTerms = [...titleWords, recipe?.cuisine].filter(
            Boolean
          ) as string[];
          photos = await fetchMealDbImages(ingredientNames, nameTerms, 6);
          imageSource = photos.length > 0 ? 'themealdb' : 'stock';
        }

        // 3) Last resort: a SINGLE-tag loremflickr food photo. (loremflickr ANDs
        //    multiple comma tags and returns a junk default when none match, so
        //    we use one broad tag that always resolves to a food photo.)
        const lock = Math.abs(
          Array.from(recipeId).reduce((h, c) => (h * 31 + c.charCodeAt(0)) | 0, 7)
        );
        const image =
          photos[0] || `https://loremflickr.com/640/480/food?lock=${lock}`;
        const stepImages = photos;

        return {
          ...recipe,
          id: recipeId,
          title: finalTitle,
          image,
          imageSource,
          stepImages,
        };
      })
    );

    console.log(`Recipes generated with: ${source}`);

    // Validate that we have recipes before returning
    if (!recipesWithImages || recipesWithImages.length === 0) {
      throw new Error('No recipes were generated');
    }

    // 📊 SESSION TRACKING: Registrar la generación de recetas en la sesión
    console.log(
      '📊 About to record recipe generation. userId:',
      userId,
      'recipes count:',
      recipesWithImages.length
    );
    if (userId) {
      console.log('📊 Recording recipe generation for userId:', userId);
      const recorded = sessionLimitsManager.recordRecipeGeneration(userId);
      if (!recorded) {
        console.warn(
          `⚠️ Failed to record recipe generation for user ${userId} - limit may have been exceeded`
        );
      } else {
        console.log(`📊 Daily recipe generation recorded for user ${userId}`);
        const remaining = sessionLimitsManager.getRemainingRecipes(userId);
        console.log(`📊 Remaining daily recipes for user ${userId}:`, remaining);
      }
    } else {
      console.log('⚠️ No userId provided, skipping recipe generation recording');
    }

    // 💾 CACHE: Guardar las recetas generadas en cache del servidor
    try {
      console.log('💾 Caching generated recipes in server cache...');
      // Convertir a formato compatible con cache
      const cacheableRecipes = recipesWithImages.map(recipe => ({
        id: (recipe as any).id || `recipe_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
        title: recipe.title,
        servings: (recipe as any).servings || servings,
        cookingTime: (recipe as any).cookingTime || '30 minutes',
        image: recipe.image,
        source: (recipe as any).source || source,
        ingredients: (recipe as any).ingredients || [],
        instructions: (recipe as any).instructions || [],
      }));

      // Guardar en cache del servidor
      global.serverCache.set(cacheKey, cacheableRecipes);
      console.log('✅ Recipes cached in server cache successfully');
    } catch (error) {
      console.error('❌ Error caching recipes:', error);
    }

    return NextResponse.json({
      recipes: recipesWithImages,
      count: recipesWithImages.length,
      source: source,
    });
  } catch (error) {
    console.error('Error generating recipe:', error);

    // Fallback to template generation
    try {
      console.log('Attempting fallback generation...');
      const fallbackRecipes = generateFallbackRecipes(
        ingredients,
        servings,
        count || 1,
        customTitle
      );

      // Add images based on ingredients
      const fallbackRecipesWithImages = fallbackRecipes.map((recipe, index) => {
        return {
          ...recipe,
          image: '/images/plate.png',
        };
      });

      console.log(`Fallback recipes generated: ${fallbackRecipesWithImages.length}`);

      // 📊 SESSION TRACKING: Registrar la generación de recetas fallback en la sesión
      console.log(
        '📊 About to record FALLBACK recipe generation. userId:',
        userId,
        'recipes count:',
        fallbackRecipesWithImages.length
      );
      if (userId) {
        console.log('📊 Recording FALLBACK recipe generation for userId:', userId);
        const recorded = sessionLimitsManager.recordRecipeGeneration(userId);
        if (!recorded) {
          console.warn(
            `⚠️ Failed to record FALLBACK recipe generation for user ${userId} - limit may have been exceeded`
          );
        } else {
          console.log(`📊 FALLBACK Daily recipe generation recorded for user ${userId}`);
          const remaining = sessionLimitsManager.getRemainingRecipes(userId);
          console.log(`📊 Remaining daily recipes for user ${userId}:`, remaining);
        }
      } else {
        console.log('⚠️ No userId provided, skipping FALLBACK recipe generation recording');
      }

      // 💾 CACHE: Guardar las recetas fallback en cache del servidor
      try {
        console.log('💾 Caching fallback recipes in server cache...');
        // Convertir a formato compatible con cache
        const cacheableFallbackRecipes = fallbackRecipesWithImages.map(recipe => ({
          id: `fallback_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
          title: recipe.title,
          servings: recipe.servings || servings,
          cookingTime: recipe.cookingTime || '30 minutes',
          image: recipe.image,
          source: recipe.source || 'fallback',
          ingredients: recipe.ingredients.map(ing => ing.name) || [],
          instructions: recipe.instructions || [],
        }));

        // Guardar en cache del servidor
        if (global.serverCache) {
          const fallbackCacheKey = `recipes_${ingredients.sort().join(',')}_${servings}`;
          global.serverCache.set(fallbackCacheKey, cacheableFallbackRecipes);
        }
        console.log('✅ Fallback recipes cached in server cache successfully');
      } catch (error) {
        console.error('❌ Error caching fallback recipes:', error);
      }

      return NextResponse.json({
        recipes: fallbackRecipesWithImages,
        count: fallbackRecipesWithImages.length,
        source: 'fallback',
      });
    } catch (fallbackError) {
      console.error('Fallback generation also failed:', fallbackError);
      return NextResponse.json({ error: 'Failed to generate recipes' }, { status: 500 });
    }
  }
}

interface FallbackRecipe {
  title: string;
  description: string;
  ingredients: Array<{
    name: string;
    quantity: number | string;
    unit: string;
  }>;
  instructions: string[];
  cookingTime: string;
  prepTime: string;
  totalTime: string;
  cuisine: string;
  servings: number;
  source: string;
}

function generateFallbackRecipes(
  ingredients: string[],
  servings: number,
  count: number = 1,
  customTitle?: string
): FallbackRecipe[] {
  const recipes = [];

  // Analizar los ingredientes para determinar el tipo de plato
  const mainIngredient = ingredients[0]?.toLowerCase() || 'chicken';
  const secondaryIngredient = ingredients[1]?.toLowerCase() || 'vegetables';

  // Determinar el tipo de cocina basado en los ingredientes
  const getCuisineFromIngredients = (ingredients: string[]): string => {
    const ingredientStr = ingredients.join(' ').toLowerCase();

    if (
      ingredientStr.includes('pasta') ||
      ingredientStr.includes('tomato') ||
      ingredientStr.includes('basil')
    ) {
      return 'Italian';
    } else if (
      ingredientStr.includes('rice') ||
      ingredientStr.includes('soy') ||
      ingredientStr.includes('ginger')
    ) {
      return 'Asian';
    } else if (
      ingredientStr.includes('tortilla') ||
      ingredientStr.includes('chili') ||
      ingredientStr.includes('lime')
    ) {
      return 'Mexican';
    } else if (
      ingredientStr.includes('curry') ||
      ingredientStr.includes('coconut') ||
      ingredientStr.includes('turmeric')
    ) {
      return 'Indian';
    } else if (
      ingredientStr.includes('fish') ||
      ingredientStr.includes('lemon') ||
      ingredientStr.includes('olive')
    ) {
      return 'Mediterranean';
    } else if (
      ingredientStr.includes('beef') ||
      ingredientStr.includes('wine') ||
      ingredientStr.includes('herbs')
    ) {
      return 'French';
    } else if (
      ingredientStr.includes('lemongrass') ||
      ingredientStr.includes('fish sauce') ||
      ingredientStr.includes('lime')
    ) {
      return 'Thai';
    }

    return 'International';
  };

  // Cuisines con sus características específicas
  const cuisineData: Record<
    string,
    {
      regionalNames: string[];
      methods: string[];
      spices: string[];
      baseIngredients: string[];
    }
  > = {
    Italian: {
      regionalNames: [
        'Tuscan',
        'Sicilian',
        'Lombard',
        'Piedmont',
        'Venetian',
        'Roman',
        'Neapolitan',
      ],
      methods: ['Braised', 'Sautéed', 'Roasted', 'Grilled', 'Baked'],
      spices: ['basil', 'oregano', 'rosemary', 'thyme', 'garlic', 'olive oil'],
      baseIngredients: ['olive oil', 'garlic', 'onion', 'parmesan cheese', 'fresh herbs'],
    },
    Mexican: {
      regionalNames: ['Oaxacan', 'Yucatecan', 'Poblano', 'Veracruzano', 'Jalisciense'],
      methods: ['Grilled', 'Sautéed', 'Braised', 'Roasted', 'Fried'],
      spices: ['cumin', 'chili powder', 'oregano', 'garlic', 'cilantro', 'lime'],
      baseIngredients: ['onion', 'garlic', 'lime', 'cilantro', 'jalapeño', 'tortillas'],
    },
    Asian: {
      regionalNames: ['Cantonese', 'Sichuan', 'Hunan', 'Shandong', 'Fujian'],
      methods: ['Stir-fried', 'Steamed', 'Braised', 'Grilled', 'Deep-fried'],
      spices: ['ginger', 'garlic', 'soy sauce', 'sesame oil', 'star anise'],
      baseIngredients: ['ginger', 'garlic', 'soy sauce', 'sesame oil', 'green onions'],
    },
    Mediterranean: {
      regionalNames: ['Provençal', 'Andalusian', 'Catalan', 'Greek', 'Turkish'],
      methods: ['Grilled', 'Roasted', 'Sautéed', 'Baked', 'Braised'],
      spices: ['oregano', 'basil', 'thyme', 'rosemary', 'garlic', 'lemon'],
      baseIngredients: ['olive oil', 'garlic', 'lemon', 'herbs', 'tomatoes'],
    },
    French: {
      regionalNames: ['Burgundian', 'Norman', 'Provençal', 'Languedoc', 'Alsacian'],
      methods: ['Braised', 'Sautéed', 'Roasted', 'Baked', 'Grilled'],
      spices: ['thyme', 'rosemary', 'tarragon', 'bay leaves', 'shallots'],
      baseIngredients: ['butter', 'shallots', 'white wine', 'herbs', 'dijon mustard'],
    },
    Indian: {
      regionalNames: ['Punjabi', 'Bengali', 'Gujarati', 'Maharashtrian', 'Tamil'],
      methods: ['Curried', 'Tandoori', 'Sautéed', 'Braised', 'Steamed'],
      spices: ['cumin', 'coriander', 'turmeric', 'cardamom', 'ginger'],
      baseIngredients: ['onion', 'garlic', 'ginger', 'tomatoes', 'coconut milk'],
    },
    Thai: {
      regionalNames: ['Northern', 'Central', 'Southern', 'Isaan', 'Bangkok'],
      methods: ['Stir-fried', 'Curried', 'Grilled', 'Steamed', 'Deep-fried'],
      spices: ['lemongrass', 'galangal', 'fish sauce', 'lime', 'basil'],
      baseIngredients: ['fish sauce', 'lime', 'basil', 'mint', 'coconut milk'],
    },
  };

  for (let i = 0; i < count; i++) {
    // Determinar la cocina basada en los ingredientes reales
    const detectedCuisine = getCuisineFromIngredients(ingredients);
    const cuisine = cuisineData[detectedCuisine] || cuisineData['Italian'];

    // Generar variedad en método y región

    const methods = cuisine.methods;
    const randomMethod = methods[i % methods.length];

    const regions = cuisine.regionalNames;
    const randomRegion = regions[i % regions.length];

    // Usar los ingredientes reales proporcionados con variación
    const mainIngredient = ingredients[i % ingredients.length] || ingredients[0] || 'Chicken';
    const secondaryIngredient =
      ingredients[(i + 1) % ingredients.length] || ingredients[1] || 'Vegetables';

    // Generar ingredientes más realistas con variedad
    const mainIngredients = ingredients.map((ing, index) => ({
      name: ing,
      quantity: Math.ceil(servings / 2) + i * 2 + index,
      unit: index % 2 === 0 ? 'pieces' : 'grams',
    }));

    // Agregar ingredientes base de la cocina con rotación (sin duplicados)
    const additionalIngredients = cuisine.baseIngredients
      .slice(i % cuisine.baseIngredients.length, (i % cuisine.baseIngredients.length) + 3)
      .map((ing: string, index: number) => ({
        name: ing,
        quantity: (index + i + 1).toString(),
        unit: ing.includes('oil') ? 'tbsp' : ing.includes('sauce') ? 'tbsp' : 'pieces',
      }));

    // Filtrar ingredientes duplicados y combinar
    const filteredAdditional = filterDuplicateIngredients(mainIngredients, additionalIngredients);
    const allIngredients = [...mainIngredients, ...filteredAdditional];

    // Aplicar deduplicación final para asegurar que no hay duplicados
    const recipeIngredients = deduplicateIngredients(allIngredients);

    // Generar instrucciones más detalladas con variedad
    const instructionTemplates = [
      [
        `Prepare and clean ${ingredients.join(', ')} thoroughly`,
        `Heat oil in a large pan and ${randomMethod.toLowerCase()} the ${mainIngredient} until golden brown`,
        `Add ${secondaryIngredient} and ${cuisine.spices.slice(0, 2).join(', ')}`,
        `Cook for 8-10 minutes until all ingredients are well combined`,
        `Season with ${cuisine.spices.slice(2, 4).join(' and ')} to taste`,
        `Garnish with fresh herbs and serve hot with ${cuisine.baseIngredients[0]}`,
      ],
      [
        `Wash and prepare ${ingredients.join(', ')} for cooking`,
        `In a heated pan, ${randomMethod.toLowerCase()} ${mainIngredient} with aromatic spices`,
        `Incorporate ${secondaryIngredient} and add ${cuisine.spices.slice(1, 3).join(', ')}`,
        `Simmer for 10-12 minutes until flavors meld together`,
        `Adjust seasoning with ${cuisine.spices.slice(3, 5).join(' and ')}`,
        `Finish with a drizzle of ${cuisine.baseIngredients[1]} and serve immediately`,
      ],
      [
        `Begin by preparing ${ingredients.join(', ')} as specified`,
        `Heat a skillet and ${randomMethod.toLowerCase()} ${mainIngredient} to perfection`,
        `Combine ${secondaryIngredient} with ${cuisine.spices.slice(2, 4).join(', ')}`,
        `Allow to cook for 6-8 minutes until well integrated`,
        `Enhance with ${cuisine.spices.slice(4, 6).join(' and ')} for depth`,
        `Present beautifully garnished with ${cuisine.baseIngredients[2]}`,
      ],
    ];

    const instructions = instructionTemplates[i % instructionTemplates.length];

    const cookingTime = 20 + i * 5 + Math.floor(Math.random() * 10);
    const prepTime = 10 + i * 3 + Math.floor(Math.random() * 8);
    const totalTime = cookingTime + prepTime;

    // Usar título personalizado si está disponible y es la primera receta
    const finalTitle =
      customTitle && i === 0
        ? customTitle
        : `${randomRegion} ${randomMethod} ${mainIngredient} ${detectedCuisine} Style`;

    recipes.push({
      title: finalTitle,
      description: `A flavorful ${detectedCuisine.toLowerCase()} dish featuring ${mainIngredient} with authentic ${cuisine.spices
        .slice(0, 2)
        .join(' and ')} flavors`,
      ingredients: recipeIngredients,
      instructions: instructions,
      cookingTime: `${cookingTime} minutes`,
      prepTime: `${prepTime} minutes`,
      totalTime: `${totalTime} minutes`,
      cuisine: detectedCuisine,
      servings: servings,
      source: 'fallback-enhanced',
    });
  }

  return recipes;
}
