import { NextRequest, NextResponse } from "next/server";
import {
  generateRecipeWithOpenAI,
  isOpenAIServiceAvailable,
} from "@/services/openaiRecipeService";
import {
  generateRecipeWithGemini,
  generateMultipleRecipesWithGemini,
  isGeminiServiceAvailable,
} from "@/services/geminiService";
import {
  generateRecipeImageWithOpenAI,
  isOpenAIImageServiceAvailable,
} from "@/services/openaiImageService";

export async function POST(request: NextRequest) {
  let ingredients: string[] = [];
  let servings: number = 2;
  let cuisine: string = "international";
  let count: number = 1;

  try {
    const requestData = await request.json();
    ingredients = requestData.ingredients || ingredients;
    servings = requestData.servings || servings;
    cuisine = requestData.cuisine || cuisine;
    count = requestData.count || count;

    if (
      !ingredients ||
      !Array.isArray(ingredients) ||
      ingredients.length === 0
    ) {
      return NextResponse.json(
        { error: "Ingredients are required and must be an array" },
        { status: 400 }
      );
    }

    if (!servings || servings < 1) {
      return NextResponse.json(
        { error: "Valid servings count is required" },
        { status: 400 }
      );
    }

    let recipes;
    let source = "gemini-fallback";

    // Primero intentar con OpenAI GPT-3.5-turbo
    if (isOpenAIServiceAvailable()) {
      console.log("🎯 Using OpenAI GPT-3.5-turbo for recipe generation");
      try {
        const openaiResponse = await generateRecipeWithOpenAI({
          ingredients,
          servings,
          cuisine,
          count: count || 1,
        });

        if (openaiResponse.recipes && openaiResponse.recipes.length > 0) {
          recipes = openaiResponse.recipes;
          source = "openai-gpt4";
        } else {
          throw new Error("No recipes generated by OpenAI");
        }
      } catch (error) {
        console.error(
          "OpenAI recipe generation failed, falling back to Gemini:",
          error
        );
        // Fallback a Gemini
        if (count && count > 1) {
          recipes = await generateMultipleRecipesWithGemini(
            ingredients,
            servings,
            count
          );
        } else {
          const recipe = await generateRecipeWithGemini(
            ingredients,
            servings,
            cuisine
          );
          recipes = [recipe];
        }
        source = "gemini-fallback";
      }
    } else {
      // Usar Gemini directamente si OpenAI no está disponible
      console.log("🔄 Using Gemini for recipe generation");
      if (count && count > 1) {
        recipes = await generateMultipleRecipesWithGemini(
          ingredients,
          servings,
          count
        );
      } else {
        const recipe = await generateRecipeWithGemini(
          ingredients,
          servings,
          cuisine
        );
        recipes = [recipe];
      }
      source = "gemini-fallback";
    }

    // Add images to recipes - generate only one image per recipe
    const recipesWithImages = await Promise.all(
      recipes.map(async (recipe) => {
        try {
          console.log(`🎨 Generating image for: ${recipe.title}`);

          // Generate image using OpenAI DALL-E
          const image = await generateRecipeImageWithOpenAI({
            recipeName: recipe.title,
            ingredients,
            cuisine,
            style: "photorealistic",
          });

          console.log(`✅ Image generated for: ${recipe.title}`);
          return {
            ...recipe,
            image: image || "/images/plate.png",
            imageSource: image ? "ai-generated" : "fallback",
          };
        } catch (error) {
          console.error(
            `❌ Error getting image for recipe: ${recipe.title}`,
            error
          );
          return {
            ...recipe,
            image: "/images/plate.png",
            imageSource: "fallback",
          };
        }
      })
    );

    console.log(`Recipes generated with: ${source}`);

    // Validate that we have recipes before returning
    if (!recipesWithImages || recipesWithImages.length === 0) {
      throw new Error("No recipes were generated");
    }

    return NextResponse.json({
      recipes: recipesWithImages,
      count: recipesWithImages.length,
      source: source,
    });
  } catch (error) {
    console.error("Error generating recipe:", error);

    // Fallback to template generation
    try {
      console.log("Attempting fallback generation...");
      const fallbackRecipes = generateFallbackRecipes(
        ingredients,
        servings,
        count || 1
      );

      // Add images based on ingredients
      const fallbackRecipesWithImages = fallbackRecipes.map((recipe, index) => {
        return {
          ...recipe,
          image: "/images/plate.png",
        };
      });

      console.log(
        `Fallback recipes generated: ${fallbackRecipesWithImages.length}`
      );

      return NextResponse.json({
        recipes: fallbackRecipesWithImages,
        count: fallbackRecipesWithImages.length,
        source: "fallback",
      });
    } catch (fallbackError) {
      console.error("Fallback generation also failed:", fallbackError);
      return NextResponse.json(
        { error: "Failed to generate recipes" },
        { status: 500 }
      );
    }
  }
}

function generateFallbackRecipes(
  ingredients: string[],
  servings: number,
  count: number = 1
): any[] {
  const recipes = [];

  // Analizar los ingredientes para determinar el tipo de plato
  const mainIngredient = ingredients[0]?.toLowerCase() || "chicken";
  const secondaryIngredient = ingredients[1]?.toLowerCase() || "vegetables";

  // Determinar el tipo de cocina basado en los ingredientes
  const getCuisineFromIngredients = (ingredients: string[]): string => {
    const ingredientStr = ingredients.join(" ").toLowerCase();

    if (
      ingredientStr.includes("pasta") ||
      ingredientStr.includes("tomato") ||
      ingredientStr.includes("basil")
    ) {
      return "Italian";
    } else if (
      ingredientStr.includes("rice") ||
      ingredientStr.includes("soy") ||
      ingredientStr.includes("ginger")
    ) {
      return "Asian";
    } else if (
      ingredientStr.includes("tortilla") ||
      ingredientStr.includes("chili") ||
      ingredientStr.includes("lime")
    ) {
      return "Mexican";
    } else if (
      ingredientStr.includes("curry") ||
      ingredientStr.includes("coconut") ||
      ingredientStr.includes("turmeric")
    ) {
      return "Indian";
    } else if (
      ingredientStr.includes("fish") ||
      ingredientStr.includes("lemon") ||
      ingredientStr.includes("olive")
    ) {
      return "Mediterranean";
    } else if (
      ingredientStr.includes("beef") ||
      ingredientStr.includes("wine") ||
      ingredientStr.includes("herbs")
    ) {
      return "French";
    } else if (
      ingredientStr.includes("lemongrass") ||
      ingredientStr.includes("fish sauce") ||
      ingredientStr.includes("lime")
    ) {
      return "Thai";
    }

    return "International";
  };

  // Cuisines con sus características específicas
  const cuisineData: Record<
    string,
    {
      regionalNames: string[];
      methods: string[];
      spices: string[];
      baseIngredients: string[];
    }
  > = {
    Italian: {
      regionalNames: [
        "Tuscan",
        "Sicilian",
        "Lombard",
        "Piedmont",
        "Venetian",
        "Roman",
        "Neapolitan",
      ],
      methods: ["Braised", "Sautéed", "Roasted", "Grilled", "Baked"],
      spices: ["basil", "oregano", "rosemary", "thyme", "garlic", "olive oil"],
      baseIngredients: [
        "olive oil",
        "garlic",
        "onion",
        "parmesan cheese",
        "fresh herbs",
      ],
    },
    Mexican: {
      regionalNames: [
        "Oaxacan",
        "Yucatecan",
        "Poblano",
        "Veracruzano",
        "Jalisciense",
      ],
      methods: ["Grilled", "Sautéed", "Braised", "Roasted", "Fried"],
      spices: [
        "cumin",
        "chili powder",
        "oregano",
        "garlic",
        "cilantro",
        "lime",
      ],
      baseIngredients: [
        "onion",
        "garlic",
        "lime",
        "cilantro",
        "jalapeño",
        "tortillas",
      ],
    },
    Asian: {
      regionalNames: ["Cantonese", "Sichuan", "Hunan", "Shandong", "Fujian"],
      methods: ["Stir-fried", "Steamed", "Braised", "Grilled", "Deep-fried"],
      spices: ["ginger", "garlic", "soy sauce", "sesame oil", "star anise"],
      baseIngredients: [
        "ginger",
        "garlic",
        "soy sauce",
        "sesame oil",
        "green onions",
      ],
    },
    Mediterranean: {
      regionalNames: ["Provençal", "Andalusian", "Catalan", "Greek", "Turkish"],
      methods: ["Grilled", "Roasted", "Sautéed", "Baked", "Braised"],
      spices: ["oregano", "basil", "thyme", "rosemary", "garlic", "lemon"],
      baseIngredients: ["olive oil", "garlic", "lemon", "herbs", "tomatoes"],
    },
    French: {
      regionalNames: [
        "Burgundian",
        "Norman",
        "Provençal",
        "Languedoc",
        "Alsacian",
      ],
      methods: ["Braised", "Sautéed", "Roasted", "Baked", "Grilled"],
      spices: ["thyme", "rosemary", "tarragon", "bay leaves", "shallots"],
      baseIngredients: [
        "butter",
        "shallots",
        "white wine",
        "herbs",
        "dijon mustard",
      ],
    },
    Indian: {
      regionalNames: [
        "Punjabi",
        "Bengali",
        "Gujarati",
        "Maharashtrian",
        "Tamil",
      ],
      methods: ["Curried", "Tandoori", "Sautéed", "Braised", "Steamed"],
      spices: ["cumin", "coriander", "turmeric", "cardamom", "ginger"],
      baseIngredients: [
        "onion",
        "garlic",
        "ginger",
        "tomatoes",
        "coconut milk",
      ],
    },
    Thai: {
      regionalNames: ["Northern", "Central", "Southern", "Isaan", "Bangkok"],
      methods: ["Stir-fried", "Curried", "Grilled", "Steamed", "Deep-fried"],
      spices: ["lemongrass", "galangal", "fish sauce", "lime", "basil"],
      baseIngredients: ["fish sauce", "lime", "basil", "mint", "coconut milk"],
    },
  };

  for (let i = 0; i < count; i++) {
    // Determinar la cocina basada en los ingredientes reales
    const detectedCuisine = getCuisineFromIngredients(ingredients);
    const cuisine = cuisineData[detectedCuisine] || cuisineData["Italian"];

    // Generar variedad en método y región

    const methods = cuisine.methods;
    const randomMethod = methods[i % methods.length];

    const regions = cuisine.regionalNames;
    const randomRegion = regions[i % regions.length];

    // Usar los ingredientes reales proporcionados con variación
    const mainIngredient =
      ingredients[i % ingredients.length] || ingredients[0] || "Chicken";
    const secondaryIngredient =
      ingredients[(i + 1) % ingredients.length] ||
      ingredients[1] ||
      "Vegetables";

    // Generar ingredientes más realistas con variedad
    const recipeIngredients = [
      ...ingredients.map((ing, index) => ({
        name: ing,
        quantity: Math.ceil(servings / 2) + i * 2 + index,
        unit: index % 2 === 0 ? "pieces" : "grams",
      })),
      // Agregar ingredientes base de la cocina con rotación
      ...cuisine.baseIngredients
        .slice(
          i % cuisine.baseIngredients.length,
          (i % cuisine.baseIngredients.length) + 3
        )
        .map((ing: string, index: number) => ({
          name: ing,
          quantity: (index + i + 1).toString(),
          unit: ing.includes("oil")
            ? "tbsp"
            : ing.includes("sauce")
            ? "tbsp"
            : "pieces",
        })),
    ];

    // Generar instrucciones más detalladas con variedad
    const instructionTemplates = [
      [
        `Prepare and clean ${ingredients.join(", ")} thoroughly`,
        `Heat oil in a large pan and ${randomMethod.toLowerCase()} the ${mainIngredient} until golden brown`,
        `Add ${secondaryIngredient} and ${cuisine.spices
          .slice(0, 2)
          .join(", ")}`,
        `Cook for 8-10 minutes until all ingredients are well combined`,
        `Season with ${cuisine.spices.slice(2, 4).join(" and ")} to taste`,
        `Garnish with fresh herbs and serve hot with ${cuisine.baseIngredients[0]}`,
      ],
      [
        `Wash and prepare ${ingredients.join(", ")} for cooking`,
        `In a heated pan, ${randomMethod.toLowerCase()} ${mainIngredient} with aromatic spices`,
        `Incorporate ${secondaryIngredient} and add ${cuisine.spices
          .slice(1, 3)
          .join(", ")}`,
        `Simmer for 10-12 minutes until flavors meld together`,
        `Adjust seasoning with ${cuisine.spices.slice(3, 5).join(" and ")}`,
        `Finish with a drizzle of ${cuisine.baseIngredients[1]} and serve immediately`,
      ],
      [
        `Begin by preparing ${ingredients.join(", ")} as specified`,
        `Heat a skillet and ${randomMethod.toLowerCase()} ${mainIngredient} to perfection`,
        `Combine ${secondaryIngredient} with ${cuisine.spices
          .slice(2, 4)
          .join(", ")}`,
        `Allow to cook for 6-8 minutes until well integrated`,
        `Enhance with ${cuisine.spices.slice(4, 6).join(" and ")} for depth`,
        `Present beautifully garnished with ${cuisine.baseIngredients[2]}`,
      ],
    ];

    const instructions = instructionTemplates[i % instructionTemplates.length];

    const cookingTime = 20 + i * 5 + Math.floor(Math.random() * 10);
    const prepTime = 10 + i * 3 + Math.floor(Math.random() * 8);
    const totalTime = cookingTime + prepTime;

    recipes.push({
      title: `${randomRegion} ${randomMethod} ${mainIngredient} ${detectedCuisine} Style`,
      description: `A flavorful ${detectedCuisine.toLowerCase()} dish featuring ${mainIngredient} with authentic ${cuisine.spices
        .slice(0, 2)
        .join(" and ")} flavors`,
      ingredients: recipeIngredients,
      instructions: instructions,
      cookingTime: `${cookingTime} minutes`,
      prepTime: `${prepTime} minutes`,
      totalTime: `${totalTime} minutes`,
      cuisine: detectedCuisine,
      servings: servings,
      source: "fallback-enhanced",
    });
  }

  return recipes;
}
