/**
 * Utilidades para generación de recetas - Enfoque funcional
 * Divide la lógica compleja en funciones más pequeñas y especializadas
 */

import { CustomRecipe } from "./recipeService";
import { ParsedRecipe } from "./geminiService";

// Tipos para las funciones utilitarias
interface RecipeGenerationParams {
  ingredients: string[];
  servings: number;
  cuisine: string;
}

interface RecipeWithImage extends CustomRecipe {
  image: string | null;
  source: string;
}

interface RecipeGenerationResult {
  success: boolean;
  recipe?: RecipeWithImage;
  error?: string;
}

/**
 * Genera una receta usando OpenAI GPT-4
 * Función pura que solo se encarga de la generación con OpenAI
 */
export const generateWithOpenAI = async (
  params: RecipeGenerationParams
): Promise<RecipeGenerationResult> => {
  try {
    const { generateRecipeWithOpenAI } = await import("./openaiRecipeService");
    const { isOpenAIServiceAvailable } = await import("./openaiRecipeService");

    if (!isOpenAIServiceAvailable()) {
      return { success: false, error: "OpenAI service not available" };
    }

    console.log("🎯 Using OpenAI GPT-4 for recipe generation");
    const response = await generateRecipeWithOpenAI({
      ingredients: params.ingredients,
      servings: params.servings,
      cuisine: params.cuisine,
      count: 1,
    });

    if (!response.recipes || response.recipes.length === 0) {
      return { success: false, error: "No recipes generated by OpenAI" };
    }

    return { success: true, recipe: response.recipes[0] as RecipeWithImage };
  } catch (error) {
    return {
      success: false,
      error:
        error instanceof Error ? error.message : "OpenAI generation failed",
    };
  }
};

/**
 * Genera una receta usando Gemini
 * Función pura que solo se encarga de la generación con Gemini
 */
export const generateWithGemini = async (
  params: RecipeGenerationParams
): Promise<RecipeGenerationResult> => {
  try {
    const { generateRecipeWithGemini } = await import("./geminiService");

    console.log("🔄 Using Gemini for recipe generation");
    const recipe = await generateRecipeWithGemini(
      params.ingredients,
      params.servings,
      params.cuisine
    );

    if (!recipe) {
      return { success: false, error: "No recipe generated by Gemini" };
    }

    return { success: true, recipe: recipe as RecipeWithImage };
  } catch (error) {
    return {
      success: false,
      error:
        error instanceof Error ? error.message : "Gemini generation failed",
    };
  }
};

/**
 * Obtiene la imagen para una receta
 * Función pura que solo se encarga de obtener imágenes
 */
export const getRecipeImage = async (
  title: string,
  ingredients: string[]
): Promise<string | null> => {
  try {
    const { getRecipeImage: getImage } = await import("./recipeService");
    return await getImage(title, ingredients);
  } catch (error) {
    console.error("Error getting recipe image:", error);
    return null;
  }
};

/**
 * Agrega imagen a una receta
 * Función pura que transforma una receta agregando su imagen
 */
export const addImageToRecipe = async (
  recipe: CustomRecipe,
  ingredients: string[],
  source: string
): Promise<RecipeWithImage> => {
  const image = await getRecipeImage(recipe.title, ingredients);

  return {
    ...recipe,
    image,
    source,
  };
};

/**
 * Genera recetas múltiples usando OpenAI
 * Función especializada para generación múltiple con OpenAI
 */
export const generateMultipleWithOpenAI = async (
  params: RecipeGenerationParams & { count: number }
): Promise<RecipeWithImage[]> => {
  try {
    const { generateRecipeWithOpenAI } = await import("./openaiRecipeService");
    const { isOpenAIServiceAvailable } = await import("./openaiRecipeService");

    if (!isOpenAIServiceAvailable()) {
      throw new Error("OpenAI service not available");
    }

    console.log("🎯 Using OpenAI GPT-4 for multiple recipe generation");
    const response = await generateRecipeWithOpenAI({
      ingredients: params.ingredients,
      servings: params.servings,
      cuisine: params.cuisine,
      count: params.count,
    });

    if (!response.recipes || response.recipes.length === 0) {
      throw new Error("No recipes generated by OpenAI");
    }

    // Procesar imágenes en paralelo
    const recipesWithImages = await Promise.all(
      response.recipes.map(async (recipe) => {
        try {
          return await addImageToRecipe(
            recipe as CustomRecipe,
            params.ingredients,
            "openai-gpt4"
          );
        } catch (error) {
          console.error("Error getting image for recipe:", error);
          return {
            ...recipe,
            image: null,
            source: "openai-gpt4",
          } as RecipeWithImage;
        }
      })
    );

    return recipesWithImages;
  } catch (error) {
    throw new Error(
      `OpenAI multiple generation failed: ${
        error instanceof Error ? error.message : "Unknown error"
      }`
    );
  }
};

/**
 * Genera recetas múltiples usando Gemini
 * Función especializada para generación múltiple con Gemini
 */
export const generateMultipleWithGemini = async (
  params: RecipeGenerationParams & { count: number }
): Promise<RecipeWithImage[]> => {
  try {
    const { generateMultipleRecipesWithGemini } = await import(
      "./geminiService"
    );

    console.log("🔄 Using Gemini for multiple recipe generation");
    const recipes = await generateMultipleRecipesWithGemini(
      params.ingredients,
      params.servings,
      params.count
    );

    // Procesar imágenes en paralelo
    const recipesWithImages = await Promise.all(
      recipes.map(async (recipe) => {
        try {
          return await addImageToRecipe(
            recipe as CustomRecipe,
            params.ingredients,
            "gemini-fallback"
          );
        } catch (error) {
          console.error("Error getting image for recipe:", error);
          return {
            ...recipe,
            image: null,
            source: "gemini-fallback",
          } as RecipeWithImage;
        }
      })
    );

    return recipesWithImages;
  } catch (error) {
    throw new Error(
      `Gemini multiple generation failed: ${
        error instanceof Error ? error.message : "Unknown error"
      }`
    );
  }
};

/**
 * Estrategia de fallback para generación de recetas
 * Función pura que maneja el fallback cuando los servicios principales fallan
 */
export const generateFallbackRecipe = async (
  params: RecipeGenerationParams
): Promise<RecipeWithImage> => {
  const { generateCustomRecipe } = await import("./recipeService");

  console.log("🔄 Using fallback recipe generation");
  const recipe = generateCustomRecipe(params.ingredients, params.servings);

  return {
    ...recipe,
    image: null,
    source: "fallback-template",
  };
};

/**
 * Estrategia de fallback para generación múltiple de recetas
 * Función pura que maneja el fallback para múltiples recetas
 */
export const generateMultipleFallbackRecipes = async (
  params: RecipeGenerationParams & { count: number }
): Promise<RecipeWithImage[]> => {
  const { generateMultipleCustomRecipes } = await import("./recipeService");

  console.log("🔄 Using fallback multiple recipe generation");
  const recipes = generateMultipleCustomRecipes(
    params.ingredients,
    params.servings,
    params.count
  );

  return recipes.map((recipe) => ({
    ...recipe,
    image: null,
    source: "fallback-template",
  }));
};
